### Criar empresa
POST http://localhost:8080/api/v1/empresas
Content-Type: application/json

{
}

### Listar todos os empresas
GET  http://localhost:8080/api/v1/empresas

### Listar empresa por ID
GET http://localhost:8080/api/v1/empresas/1

### Excluir empresa por ID

DELETE http://localhost:8080/api/v1/empresas/1

### Atualizar empresa
 
PUT  http://localhost:8080/api/v1/empresas/1
Content-Type: application/json
 
{
}
 